### ISSUE TITLE
Blue Background Inaccuracies

### ISSUE THREAD

**Issue by GabrielMiceli** [greggman/html5bytebeat#10]
I found out that I could put arbitrary images in the blue background by using an array. As I was doing so, I discovered a few errors with the blue background rendering. Specifically, numbers 20, 36, 37, 52, and 53, modulo 256, get rendered as each minus 1.
![image](https://user-images.githubusercontent.com/30030529/65335149-7ddabb00-db89-11e9-95c7-931c7152cb0e.png)

**Comment by greggman** [comment]
doh!

fixed
