### ISSUE TITLE
Currently not online

### ISSUE THREAD

**Issue by toddwords** [greggman/html5bytebeat#11]
HTML5Bytebeat is not currently accessible at http://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html

**Comment by greggman** [comment]
Sorry, it should be back

**Comment by DevEd2** [comment]
FYI, it's down again

**Comment by greggman** [comment]
Sorry. [Letsencrypy broke it](https://community.letsencrypt.org/t/questions-about-renewing-before-tls-alpn-01-revocations/170449) 🙁

Should be up now
