### ISSUE TITLE
h

### ISSUE THREAD

**Issue by G9-dev-real** [greggman/html5bytebeat#14]
Pls add signed bytebeat

**Comment by greggman** [comment]
what is signed bytebeat?

You mean 0x80 is -1?

Can't you just add 128 to the end of your expression to get the same result?

**Comment by DAriK8632** [comment]
> what is signed bytebeat?
> 
> You mean 0x80 is -1?
> 
> Can't you just add 128 to the end of your expression to get the same result?

Its like from dollchan net bytebeat JUST ADD IT pls
