### ISSUE TITLE
it's not working (im using google chrome, windows 10), it gives error "SyntaxError: Unexpected token"

### ISSUE THREAD

**Issue by danidanijr1** [greggman/html5bytebeat#19]
when i type "t" into the text box, it does not play sound, instead it gives an error, and its "SyntaxError: Unexpected token '.'"
![image](https://user-images.githubusercontent.com/94558724/190925045-2be9f9e2-6217-4cac-9a98-ac81e7c1cda7.png)
why does it do that?

**Comment by greggman** [comment]
clear your cache?

![2022_09_18-21_40_26_chrome_49](https://user-images.githubusercontent.com/234804/190950892-f0c224b7-7abc-4369-a43b-69be2f2da9de.png)
