### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by BonziWorldz** [greggman/html5bytebeat#21]
plz add funcbeat

its from sarpnt git hub io bytebeat

**Comment by greggman** [comment]
function style is already on there, tho I need more examples.

[funcbeat example](https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html#t=1&e=3&s=44100&bb=5d00000100fe010000000000000039194af031b445aedd75309df43c408c46627877a0cc4921c1c85e15b418b6426811708ef659be64d728efadc2ced4be0d68b9dea9e9f29e4ee93aef5595dd502f778c3b79c0687de279cf1f5db996aeeefd518ef358c592dd47c384db99dc011e5ef13349532959dc72591798b8126155272085e104d10091738ac1594a916d9cd2c2412c2b97fcb12df4ca14fa8d7484946f386f5a661efe8a43bcc21cd3dc35931be1222767262b6bb764fc20e109fd4acfe9a5357ca57b79707697feaf8ea7a6eba874296da0e6caeab81b2c4fb4838cce0e1303e5aef8c409db3e1f334a6f10b4179fc8e8cbe5581fe2e7964427564d64f95d9cfdc789e73cbfe46802eb247d5761cbba1c12a8de801e4e1c484cedeb9638f6f5f2ef74135a676ea275b5a5040f0f9d2a6d24c1ec13a7d2d6fa96f5725f4ac4debc09b057142acea3c728669cbaac1c07c6129222caa662c8d3d416f25196d253c72d4de7e41157c145e4145685eafccf767875f32bcca8826b1e7df571ecc962a1c38fb70e6dcecadffce13b65)

**Comment by BonziWorldz** [comment]
> function style is already on there, tho I need more examples.
> 
> [funcbeat example](https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html#t=1&e=3&s=44100&bb=5d00000100f2010000000000000039194af031b445aedd75309df43c408c46627877a0cc4921c1c85e15b418b6426811708ef659be64d728efadc2ced4be0d68b9dea9e9f29e4ee93aef5595dd502f778c3b79c0687de279cf1f5db996aeeefd518ef358c592dd47c384db99dc011e5ef13349532959dc72591798b8126155272085e104d10091738ac1594a916d9cd2c2412c2b97fcb12df4ca14fa8d7484946f386f5a661efe8a43bcc21cd3dc35931be1222767262b6bb764fc20e109fd4acfe9a5357ca57b79707697feaf8ea7a6eba874296da0e6caeab81b2c4fb4838cce0e1303e5aef8c409db3e1f334a6f10b4179fc8e8cbe5582eab061bb30cfcb8c99deb187822efc10851234647579a43124b7cb53b95629a1fce3a2f6df9a34ddd4a660fd762e9626b13f4816c3382fdcde20ecdb75fbab028066aefee7c3b2476fd0e5de69e9306130000a0a78dfa6ecba33e10342e3cf66d916ffeec14686deb970df1b4a3ad7741d23a1c4a9a36b9a8d38ef3e4ff88fd2b0cc3035cc362b57b7b2f38e568fcf846e8)

i said funcbeat, not function
