### ISSUE TITLE
HELLO

### ISSUE THREAD

**Issue by BonziWorldzalt** [greggman/html5bytebeat#23]
Please add Sinmode. Bitbeat. 2048. Sinfreq. Logmode, Logmode10. and RAW.

**Comment by greggman** [comment]
No. Please learn to code, all of those can be done by writing the correct expression in the existing modes. Adding new modes is entirely the wrong way to use bytebeat/floatbeat. 
I'd be like asking for 2X mode. You don't need 2x mode. You just multiply `t` by 2. Same with all of those other modess

**Comment by BonziWorldzalt** [comment]
ok ill learn

**Comment by BonziWorldzalt** [comment]
> No. Please learn to code, all of those can be done by writing the correct expression in the existing modes. Adding new modes is entirely the wrong way to use bytebeat/floatbeat. I'd be like asking for 2X mode. You don't need 2x mode. You just multiply `t` by 2. Same with all of those other modess

but... its like from "[Chasyxx Enchanced Bytebeat](https://chasyxx.github.io/Enhanced-Bytebeat/#enBeat-q1YqTswtyEkNSixJVbJSsjAwMFDSUUrLL8otzUkECpRoaRhUODtaWoCwnZ1GiZ2dpZqxgaaaoalmDZBjAVRdUlkA1GtQCwA=)", please add it.

Do you know understand

**Comment by greggman** [comment]
Sorry but No. The whole point of bytebeat and floatbeat is to do your own math. Putting math in the player is missing the entire point. That's not "enhanced", that's dumbed down.

Put it in bytebeat mode then use one of these expressions

```
bitBeat = value => (value & 1) * 255,
sinMode = value => Math.sin(value | 0) * 128 + 128,
m2048 = value => value>>2 & 255,
sinFreq = value => Math.sin((value * Math.PI) / 128) * 128 + 128,
logMode = value => Math.log2(value) * 32 & 255,
logMode10 = value => Math.log10(value) * 106.301699 & 255,
```

Example:

https://chasyxx.github.io/Enhanced-Bytebeat/#enBeat-q1YqTswtyEkNSixJVbJSMjQyNVDSUUrLL8otzUkECmiUKNjZKZhogkgLhRoFMNfQQEEbwjIDKi6pLABqNa4FAA==

vs

https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html#t=0&e=0&s=44100&bb=5d000001004f0000000000000000311a4aec677cec8ae0ad63f56f966e00dbc9f31d0503292b7956faf21e4219853fbfa14381906b7751d7f1c0ad3eff5f0ad42dee081705bc7d22d1b589db0e1dfff6628700

**Comment by BonziWorldzalt** [comment]
ok how about later?

**Comment by alternative-buddy** [comment]
stolen song by @JarredThePelmeni
