### ISSUE TITLE
Hey dear greggman!

### ISSUE THREAD

**Issue by G9-Dev-RealIsCool** [greggman/html5bytebeat#24]
hey. i want to make a bytebeat. but. what is the code of the sound of swatting? Sound of swatting heard from Fly Swatter :)
Dont bother us.
G9-dev-realIsCool

**Comment by BonziWorldzalt** [comment]
[Example](https://dollchan.net/bytebeat/#v3b64q1ZKzk9JVbJS0ijR0jCpMVcrsbMzNNa0s9OoA7EM1Qw11QyNzDW1QfIQEYgKLbACSzVjTTUzE02lWgA)

**Comment by G9-Dev-RealIsCool** [comment]
bruh. i need the code!!!
