### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by darik9pl** [greggman/html5bytebeat#25]
Please add sound recorder, With.
If i record, it will record. 
And if i STOP. so it will save a .WAV file

**Comment by darik9pl** [comment]
a

**Comment by greggman** [comment]
There is already a sound recorder. Click `[Save]`. Plus, your OS probably has one built in

[windows](https://support.microsoft.com/en-us/windows/sound-recorder-app-for-windows-faq-5c208478-2141-bd07-fe1d-d6d1356c1d56), [mac](https://recorder.easeus.com/screen-recording-tips/record-internal-audio-on-mac.html)

You can also record with [audacity](https://www.audacityteam.org/). Bonus, you can save in many formats.

**Comment by darik9pl** [comment]
> There is already a sound recorder. Click `[Save]`. Plus, your OS probably has one built in
> 
> [windows](https://support.microsoft.com/en-us/windows/sound-recorder-app-for-windows-faq-5c208478-2141-bd07-fe1d-d6d1356c1d56), [mac](https://recorder.easeus.com/screen-recording-tips/record-internal-audio-on-mac.html)
> 
> You can also record with [audacity](https://www.audacityteam.org/). Bonus, you can save in many formats.

im in windows 10 21h1
