### ISSUE TITLE
raining metals this is better in 8kHz

### ISSUE THREAD

**Issue by JarredTheCoder** [greggman/html5bytebeat#26]
https://dollchan.net/btb/res/225.html#225

**Comment by darik9pl** [comment]
remix: https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html#t=0&e=0&s=44100&bb=5d000001004301000000000000003a0bc3a378ddd90fdc1d2886eb7ee17519fdedbb83a22dcd6f47b79dae5e3ed7165357a4daf39e565ff835f040d78ad45dff11f213cab568f170585f7920e775670755ed6908bb053b0fa339df5355559a89d6375a9651ad39d99d66a3004fa8144040a59ac060130c370c3aac023e739051a2e5c3d642d67b2593c6156537b2e3637aa1fad3482c822e7c21097ad08c5143eeb02883384ecb2b04bc6c9e1ac66664caea877e022ca4f168b17691854ea816cfef43826509000f024b1a5d8cc4e9a5abcbad0b324724302b69656a585a7f6e114af3a4dd09f6d8728c9e4fa465c61d47b9ffe23fc4f5

**Comment by alternative-buddy** [comment]
@JarredTheCoder your name should the JarredThePelmeni
