### ISSUE TITLE
stolen song

### ISSUE THREAD

**Issue by rmtrollboxuser9** [greggman/html5bytebeat#27]
[Remix Of teaserall Double by JARREDBARA (stolen)](https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html#t=0&e=0&s=100000&v=c-pump&bb=5d00000100700600000000000000178a7d4bda3827ad898e97a06415829cb29768dd8d17ccc2298994cff61f8839f8daf5de88ce8002a7434c7e16944eb054ee2b3c090bb7c550b2de0f2205d623a3c7696dc410074abe565d6fe060c4ce80be1d85e3b7463a0a429b9ce09a0c7e248842838a1eddc4dd63da0dc0531208f5c0ec0619d219fabfbe4e21076dc3fd26d873f5e6a3bf1d04e72920196d43a39c295848888c598b3ec3e0b021ca0299531d23ccb3f06bab685fd8b51ffad15a82eafa3c642682e56c4dfd5e643c5e5e7c3957ff84a099117b58e9d8f6e98a79acc3591606ac7570f3b1ca93c1f3a3d565804975120d8595f0c8f834c39be6032e8919ed827190f83db2cf26bd315fd45612f29c6ed7a58b3ad7fe007c5dc76b7883ae5c62d0a6facccced1da701c4aa0f15a305e1ad7515fcdc4d66e561ce9412ec4950abeb205fb11adeb83b37550ae236bc675d06a4e19c2d93446aff3f83b74f35bf5d8801052d45c7ce7d127fdf825366c7e531abfff4ad09da4d3995922eb5f9040c002b9d657cc39625a4bc81ffa00228904f37ddf6cdf8f5a195502f08b4c334e75faa7b415808e49b1d03f1a0396bb61e93ca08c71c9757e6ce5eb651a5e5b94fe36d4017ef20c0cc55fea7f20091248b81d999d481f6c609695adda40402708efd7c76716b83860113c48579691ac0b0e0a812e7f79f0f25d16b9d19e5cbb0e38ca54088fd7292fb79a13c9c44709462676b1ab1d0fc7259a779138f0fa2336122aadf7a4c14fbad6e1608027158c9fed6dedc7f135cab7d28d74dfc77f6027c759a0d1220cbad384add3d5c6209da2269508ce266c619bda6deec81a8f7d4928d948cbe25ff997c2c7177b8567d9dccf36c7edcdb0ffc25972113ff1f87df8fc523b4f0bed2ca93e9e6b1c2f5dbbda87c23b93fed4410bce7304fa8ba12aea4430a4edc8d9fec56fd2a75c239ff8cd8555c838650809d8ab58ec017ffb68fae62)

help greggman jarredthecoder stole my song help :((

**Comment by alternative-buddy** [comment]
I Will quote-issue greggman to approve my support (Hope he doesnt fall for this)
