### ISSUE TITLE
HTML5ByteBeat not working in Chrome.

### ISSUE THREAD

**Issue by KeitoTobi1** [greggman/html5bytebeat#31]
As the title says.

**Comment by greggman** [comment]
What OS? what version of Chrome? Any errors in the JavaScript console? Disabled all your extensions? Have you tried clearing your cache?

It works fine in Chrome.

**Comment by kotenok2000** [comment]
I get SyntaxError: Unexpected token '.' on https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html#t=0&e=0&s=44100&bb=5d0000010063000000000000000017e07ce4793292a76e4fd26ba50e5eee5a196d720febb0554aeaa3a3dee3320db7331422f21ea7f3772914282393e89a04de943c597fe8c54a71b727ba43b0c1975d6b44c2a4b609e404ba4592ebe3381713aefff9a4e800
Chrome version 107.0.5304.107
Windows 11 Version 22H2 (Build 22621.819)
Chrome is started with these flags "C:\Program Files\Google\Chrome\Application\chrome.exe" --task-manager-show-extra-renderers --disable-backgrounding-occluded-windows --flag-switches-begin --enable-gpu-rasterization --enable-nacl --enable-quic --enable-zero-copy --force-color-profile=srgb --ignore-gpu-blocklist --enable-features=PrivacySandboxAdsAPIsOverride,InterestGroupStorage,Fledge,BiddingAndScoringDebugReportingAPI,AllowURNsInIframes,BrowsingTopics,ConversionMeasurement,FencedFrames,OverridePrivacySandboxSettingsLocalTesting,SharedStorageAPI,PrivateAggregationApi --enable-features=PrivacySandboxSettings3:disable-dialog-for-testing/true/show-sample-data/true,EnableFetchingAccountCapabilities,InterestGroupStorage,AdInterestGroupAPI,Fledge,FencedFrames --disable-smooth-scrolling --unsafely-treat-insecure-origin-as-secure=https://sheeps.triple6.org,https://derpinxghr4jpjk4h4acjxyrx4rcwtk7ggjyt32uyaxgodqq7cfewuqd.onion --enable-features=PrivacySandboxSettings3:disable-dialog-for-testing/true/show-sample-data/true,EnableFetchingAccountCapabilities,InterestGroupStorage,AdInterestGroupAPI,Fledge,FencedFrames,CanvasOopRasterization,ChromeLabs,EnableDrDc,RawDraw --disable-features=BackForwardCache,ClosedTabCache,TabHoverCardImages,ThrottleDisplayNoneAndVisibilityHiddenCrossOriginIframes --flag-switches-end

**Comment by kotenok2000** [comment]
Can you disable some flags  and check if it fixes it?

**Comment by greggman** [comment]
Does it work with just

"C:\Program Files\Google\Chrome\Application\chrome.exe" --use-data-dir=c:\temp123 https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html

?

**Comment by KeitoTobi1** [comment]
I tried it and it was cured, but in my case it was like this:
```
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --use-data-dir=c:\temp123 https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html
```
