### ISSUE TITLE
No 16 khz/16000 hz option, realy helpfull with some byteabeat

### ISSUE THREAD

**Issue by Tr3yWay996** [greggman/html5bytebeat#35]
So like i said there is no any 16khz option onlt 11 and we jump to 22 instantky idk why, is it because its not posible on HTML 5 ?
Because yeah it completly destruct the chosen byteabeat if it need to be ran in a specific range of khz/hz.

I tried to modificate the html myselft because everything is clientside, atleast for the music composition and the graphics maybe ? idk

But yeah that prety much it, apart of that i love this bytebeat composer and with his unique graphics

Yeah i forgor to say that its with the Website

**Comment by greggman** [comment]
The entire point of bytebeat is to be creative within limits. Every extra feature you ask for mean you failed to understand the entire point. If you want unlimited features then just go program without limits.

That said, you can put any sample rate you want. Just change the `s=` tag in the url

https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html#t=0&e=0&s=8000&bb=5d000001000100000000000000003a41fbffffffe0000000

https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html#t=0&e=0&s=16000&bb=5d000001000100000000000000003a41fbffffffe0000000

https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html#t=0&e=0&s=24000&bb=5d000001000100000000000000003a41fbffffffe0000000

https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html#t=0&e=0&s=96000&bb=5d000001000100000000000000003a41fbffffffe0000000
