### ISSUE TITLE
js code can access the global scope and do anything

### ISSUE THREAD

**Issue by SArpnt** [greggman/html5bytebeat#37]
try [this one out](https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html#t=0&e=0&s=8000&bb=5d000001004c0000000000000000349b4a67b8523c9bd9b6adcca0bd0e7b167415b70f4713c8e309b2a09894ca85671398617a903eb504c5cf9b11777cff3be71e91fd905c84f02c0632c1e7f98990d4cb5f7d4798a3212bc566f3ffff30400000)
```
import("data:text/javascript,document.location='/'+'/youtu.be/oHg5SJYRHA0'")
```

**Comment by jan-ale** [comment]
40ad2fa4a89727c060afe565a2cf3a27282eb35b tried to fix it, but now it shows `SyntaxError: Unexpected token 'import'`

Quotes don't fix it. Though import is a token, and we can't eval things, so maybe we could detect if the code contains import?
