### ISSUE TITLE
website doesn't work anymore

### ISSUE THREAD

**Issue by Atonal-Circuits** [greggman/html5bytebeat#38]
Hi since few days I get this error on the website: "SyntaxError: missing variable name"
no more sound. I tried Firefox, Chrome. I tried to delete cache, coockies etc... no change

**Comment by jan-ale** [comment]
maybe it's caused by 40ad2fa4a89727c060afe565a2cf3a27282eb35b? it says `SyntaxError: Unexpected token 'import'`

**Comment by jan-ale** [comment]
commit 081533daac0c85200dceef1440829bda149c9923 fixed it!
