### ISSUE TITLE
js code can access the global scope and do anything

### ISSUE THREAD

**Issue by SArpnt** [greggman/html5bytebeat#42]
[try it out](https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html#t=0&e=0&s=8000&bb=5d00000100400000000000000000331d49ffa961fb1306bb3a188fda86fa8bcc12780cd528cb3b01283a30e39ed37357f1c64ac72ccae0ee37eade31930c460f50c3f639a69fe046c9d00a6b8b3f98bbfffe30fac0)
```
function(){this.document.location='/'+'/youtu.be/oHg5SJYRHA0'}()
```

if you ran the js code in an audio worklet like [my site does](https://bytebeat.ficial.net/#5X6AAAHSyvNSy7JzM/T0Kwuycgs1kvJTy7NTc0r0cvJT04ESdiq66trq+tX5peWlOolperne6SbBntFBnk4GqjXamgCAA), you wouldn't need all the text filters and monkey patching, it would be far more secure, and it would be far more efficient.

**Comment by greggman** [comment]
The code for audio is already run in an audio worklet. The code for *some* visualization is not. Not sure when I'll have time to deal with it. I'm not super worried though. The site itself has nothing to steal. It's not site with accounts or logins or data.

I mean, you can also do [this](https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html#t=0&e=0&s=8000&bb=5d000001007d05000000000000003a07fd582f16f4dd4a471667cd9527a26a44a76b128e297ba1bb1843135866c2aa66a0263b0eee2efb30d1ffbfbbf92384465cb60abfffb9238c98cfc8af2d73f1d7611b7df019523077a1d32de1d67d428154fbb109660ca4a14bd1ac11f7c9b3aaa9e6e6c989d29477aa2b5c49eda0b597e5c89c0be7a22fa2169adec7bd099f53f8a0faa8d5cc59c9681262f26c1d9b4901ca7d673068aad8369aea59d98772d7325684f93a16996485868d9f8c8b4bc642bf6303b7f7b1b4b411dca705a70b38f52f146065869acb46659895e919d1c25ff615e640b6073e30e3f8cda41b00b199cd48b62f5354c723625b6d53631d8a609b2c015a2f0454b206d5fb3779907377743865a836119b294a09b49c726f70757a4bdb5cde3de0562e83174253ea188132346266cb2a4a12e11e736220a5580e38dc870b088017958fec38462362371b31a3f6adce2f94dedc049eae43dbba9b796cdfd621d33cac19707757f613274481ce8a1e6c6c694c42a181b9f0643f2674109e32f284b0c86e5335756f8bc20ddf60ffd73b7569ddec886f2adf60a81c77478fbca83bbc4c6cff5b7b9aaa8012352a18fff5c717a4) and I can't stop it

**Comment by SArpnt** [comment]
> The code for audio is already run in an audio worklet.

ah, i hadn't checked it recently, last i checked the website used some older audio api that ran in the main thread, and i assumed this hadn't changed because document and other such variables just aren't available in a worklet.

personally my issue with it is that the urls can be misleading (what looks like it should just play some sounds can actually do just about any network requests before you can even react) and that it could likely be used to cheat in [competitions](https://battleofthebits.com/browser/), for example, by fitting a network request into some highly obfuscated code to load extra code that extends the length of a song. there's also almost certainly increased attack surface to take advantage of browser security issues.

even without any malicious intent, i'm fairly sure that running js in the main thread makes it much easier to freeze/crash the browser (i really do not want to go about testing various methods for that right now)

**Comment by greggman** [comment]
I think it's fixed so the 2 visualizers that used the expressions locally, no longer do, I had to hack a bunch of stuff but cross my fingers it's not broken. 

<img width="746" alt="Screenshot 2024-04-27 at 11 30 08" src="https://github.com/greggman/html5bytebeat/assets/234804/8325ddf4-a850-4594-a90c-3ee253c1a1fe">


Might need to clear your cache for the newest code
