### ISSUE TITLE
my song "boots in bed" is just labelled "??"

### ISSUE THREAD

**Issue by SArpnt** [greggman/html5bytebeat#44]
* [??](https://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html#t=1&e=3&s=44100&bb=5d00000100f2010000000000000039194af031b445aedd75309df43c408c46627877a0cc4921c1c85e15b418b6426811708ef659be64d728efadc2ced4be0d68b9dea9e9f29e4ee93aef5595dd502f778c3b79c0687de279cf1f5db996aeeefd518ef358c592dd47c384db99dc011e5ef13349532959dc72591798b8126155272085e104d10091738ac1594a916d9cd2c2412c2b97fcb12df4ca14fa8d7484946f386f5a661efe8a43bcc21cd3dc35931be1222767262b6bb764fc20e109fd4acfe9a5357ca57b79707697feaf8ea7a6eba874296da0e6caeab81b2c4fb4838cce0e1303e5aef8c409db3e1f334a6f10b4179fc8e8cbe5582eab061bb30cfcb8c99deb187822efc10851234647579a43124b7cb53b95629a1fce3a2f6df9a34ddd4a660fd762e9626b13f4816c3382fdcde20ecdb75fbab028066aefee7c3b2476fd0e5de69e9306130000a0a78dfa6ecba33e10342e3cf66d916ffeec14686deb970df1b4a3ad7741d23a1c4a9a36b9a8d38ef3e4ff88fd2b0cc3035cc362b57b7b2f38e568fcf846e8)

_Originally posted by @greggman in https://github.com/greggman/html5bytebeat/issues/17#issuecomment-1247464511_

**Comment by greggman** [comment]
Sorry, what should it say? Where ever I got it from it wasn't documented.

**Comment by greggman** [comment]
changed it to `[boots in bed]`

**Comment by SArpnt** [comment]
should be `boots in bed (by SArpnt) (48k)`, and change the samplerate on it.

all my songs are posted and correctly labelled on [my bytebeat website](https://bytebeat.ficial.net)
