### ISSUE TITLE
Request: .wav export

### ISSUE THREAD

**Issue by raphaelgoulart** [greggman/html5bytebeat#6]
It would be nice having a way to export a .wav file to upload to SoundCloud, or use in videos, or...well, anything that requires an audio file.
It could be something as simple as an alert asking for the desired length of the audio in seconds, and then exporting from (t = 0) while (t < selected sample rate * desired length in seconds), I don't know how easy it'd be to implement it but it'd be really helpful.
Thanks

**Comment by greggman** [comment]
Sure, that would be a nice feature.

In the meantime you can use screen recording software to capture your system audio. Both Windows and MacOS have screen recording software built in.

**Comment by raphaelgoulart** [comment]
Thanks! That's what I've been doing currently, just thought it'd be convenient to have on the website itself.
